var GAME_LEVELS = [
  ["                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                  xxx           ",
   "                                                   xx      xx    xx!xx       x  ",
   "                                    o o      xx        qq        x!!!x       x  ",
   "                                            x                    xx!xx       x  ",
   "                                   xxxx                           xvx        x  ",
   "                                       x                                    xx  ",
   "  xx                                      o o                                x  ",
   "  x                     o                                                    x  ",
   "  x                                      xxxxx                             o x  ",
   "  x          xxxx       o                                                    x  ",
   "  x  @       xxxx               f                      f f       xxxxx       x  ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxx   xxxxxxxxxxxxxxxxxxxx     xxxxxxxxxxxxxxxxxxx  ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxx   xxxxxxxxxxxxxxxxxxxx     xxxxxxxxxxxxxxxxxxx  ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!xxxxxxxxxxxxxxxxxxxx!!!!!xxxxxxxxxxxxxxxxxxx  ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!xxxxxxxxxxxxxxxxxxxx!!!!!xxxxxxxxxxxxxxxxxxx  ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
   "                                                                                ",
   "                                                                                "],
  ["                                      x!!x                        xxxxxxx                                    x!x  ",
   "                                      x!!x                     xxxx     xxxx                                 x!x  ",
   "                                      x!!xxxxxxxxxx           xx           xx                                x!x  ",
   "                                      xx!!!!!!!!!!xx         xx             xx                               x!x  ",
   "                                       xxxxxxxxxx!!x         x                                    o   o   o  x!x  ",
   "                                                xx!x         x     o   o                                    xx!x  ",
   "                                                 x!x         x       f                        xxxxxxxxxxxxxxx!!x  ",
   "                                                 xvx         x     x   x                        !!!!!!!!!!!!!!xx  ",
   "                                                  v          xx  |       |  xxxxx        xxxxxxxxxxxxxxxxxxxxxx   ",
   "                                                  v           xx!!!!!!!!!!!xx           xv   x                    ",
   "                                                               xxxx!!!!!xxxx                 x                    ",
   "                                               xx    x            xxxxxxxxxx  o  xxx         x                    ",
   "                                               x     x                   xxxxxxxxxxxx        x                    ",
   "                                               x     x                   xxxxxxxxxxx         x                    ",
   "                                               x    xx                   xxxxxxxxxxx         x                    ",
   "                                               x     x                   xxxxxxxxxxxx        x                    ",
   "                                               x     x      o  o     x   xxxxxxxxxxx         x                    ",
   "               xxxxxxx         xx   xx         xx    x               x   xxxxxxxxxxx         x                    ",
   "              xxxxxxxxx       x x   x x        x     x     xxxxxx    x   xxxxxxxxxxxx        x                    ",
   "             xxxxxxxxxxx        x o x          x     x               x    xxxx               x                    ",
   "     @  f  f xxxxxxxxxxx  f     x   x          x    xx  f            x    xxxx               x                    ",
   "    xxx  xx  xxxxxxxxxxx        x   x          x     x               x    xxxx    xxxx       x                    ",
   "    xxx      xxxxxxxxxxx       xx o xx         x     x               x     o      xx  x      x                    ",
   "!!!!xxx!!!!!!xxxxxxxxxxx!!!!!!xx     xx!!!!!!!!xx    x!!!!!!!!!!     x     =      xx         x                    ",
   "!!!!xxx!!!!!!xxxxxxxxxxx!!!!!xx       xxxxxxxxxx     x!!!!!!!xx!     xxxxxxxxxxxxxxxx  o o  xx                    ",
   "!!!!xxx!!!!!!xxxxxxxxxxx!!!!!x    o                 xx!!!!!!xx !     xxxxxxxxxxxxxxxxx     xxx                    ",
   "!!!!xxx!!!!!!xxxxxxxxxxx!!!!!x                     xx!!!!!!xx  !     xxxxxxxxxxxxxxxxxxxxxxxxx                    ",
   "!!!!xxx!!!!!!xxxxxxxxxxx!!!!!xx       xxxxxxxxxxxxxx!!!!!!xx   !     xxxxxxxxxxxxxxxxxxxxxxxxx                    ",
   "!!!!xxx!!!!!!xxxxxxxxxxx!!!!!!xxxxxxxxx!!!!!!!!!!!!!!!!!!xx    !     xxxxxxxxxxxxxxxxxxxxxxxxx                    ",
   "!!!!xxx!!!!!!xxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xx     !     xxxxxxxxxxxxxxxxxxxxxxxxx                    "],
  ["                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                        o                                                                     ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                        x                                                                     ",
   "                                        x                                                                     ",
   "                                        x                                                                     ",
   "                                       xxx                                                                    ",
   "                                       xxx                 !!!        !!!  xxx                                ",
   "                                       xxx                 !x!        !x!                                     ",
   "                                     xxxxxxx                x          x                                      ",
   "                                      xxxxx                 x   oooo   x       xxx                            ",
   "                                x     xxxxx                 x          x      x!!!x                           ",
   "                                      xxxxx                 xxxxxxxxxxxx       xxx                            ",
   "                                     xxxxxxx      x   x      x                                                ",
   "                                      xxxxxxxxxxxxx   xxxxxxxx              x x                               ",
   "                                x     xxxxx           x                    x!!!x                              ",
   "                                      xxxxx           x                     xxx                               ",
   "                                     xxxxxxx          x                                                       ",
   "                                      xxxxx= = = =    x            xxx                                        ",
   "                                x     xxxxx           x           x!!!x                                       ",
   "                                      xxxxx    = = = =x     o      xxx       xxx                              ",
   "                                     xxxxxxx          x                     x!!!x                             ",
   "                              o   o   xxxxx           x     x                xxv        xxx                   ",
   "                                      xxxxx           x              x                 x!!!x                  ",
   "                             xxx xx   xxxxxx     o o  x!!!!!!!!!!!!!!x                   vx                   ",
   "                             xxxxxxx xxxxxxx          x!!!!!!!!!!!!!!x                                        ",
   "                             x             x   xxxxxxxxxxxxxxxxxxxxxxx                                        ",
   "                             xx           xx                                         xxx                      ",
   "  xxx                         x     x     x                                         x!!!x                xxx  ",
   "  x x                         x    xxx    x                                          xxx                 x x  ",
   "  x                           x    xxx    xxxxxxx                        xxxxx                             x  ",
   "  x                           x           x                              x   x                             x  ",
   "  x                           xx          x        xxxx      xxxx   xx   x x x                             x  ",
   "  x                                       x       |    |    |    |       x xxx                             x  ",
   "  x                 x              o o    x                              x         xxx                     x  ",
   "  x                xxx        xx          x                             xxx       x!!!x          x         x  ",
   "  x               xxxxx      xx    xxx    x                             x x        xxx          xxx        x  ",
   "  x               oxxxo     xxxxxxxxxxxxxxx  x oo x    x oo x    x oo  xx xx                    xxx        x  ",
   "  x      @          x      xxxx           x!!x    x!!!!x    x!!!!x    xx   xx                    x         x  ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxx           xxxxxxxxxxxxxxxxxxxxxxxxxxxxx     xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
   "                                                                                                              ",
   "                                                                                                              "],
  ["                                                                                                  xxx x       ",
   "                                                                                                      x       ",
   "                                                                                                  xxxxx       ",
   "                                                                                                  x           ",
   "                                                                                                  x xxx       ",
   "                          o                                                                       x x x       ",
   "                                                                                             o o oxxx x       ",
   "                   xxx                                                                                x       ",
   "       !  o  !                                                xxxxx xxxxx xxxxx xxxxx xxxxx xxxxx xxxxx       ",
   "       x     x                                                x   x x   x x   x x   x x   x x   x x           ",
   "       x= o  x            x                                   xxx x xxx x xxx x xxx x xxx x xxx x xxxxx       ",
   "       x     x                                                  x x   x x   x x   x x   x x   x x     x       ",
   "       !  o  !            o                                  xxxx xxxxx xxxxx xxxxx xxxxx xxxxx xxxxxxx       ",
   "                                                                                                              ",
   "          o              xxx                              xx                                                  ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                      xx                                                      ",
   "                   xxx         xxx                                                                            ",
   "                                                                                                              ",
   "                          o                                                     x      x                      ",
   "                                                          xx     xx                                           ",
   "             xxx         xxx         xxx                                 x                  x                 ",
   "                                                                                                              ",
   "                                                                 ||                                           ",
   "  xxxxxxxxxxx                                                                                                 ",
   "  x         x o xxxxxxxxx o xxxxxxxxx o xx                                                x                   ",
   "  x         x   x       x   x       x   x                 ||                  x     x                         ",
   "  x  @      xxxxx   o   xxxxx   o   xxxxx                                                                     ",
   "  xxxxxxx                                     xxxxx       xx     xx     xxx                                   ",
   "        x=                  =                =x   x                     xxx                                   ",
   "        xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx   x!!!!!!!!!!!!!!!!!!!!!xxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "                                                  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                                                              "]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
